spring.application.name=reseau-social

# Nom de la datasource SQL
spring.datasource.url=jdbc:mysql://localhost:3306/linkdong?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuration MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/reseau_social
spring.data.mongodb.database=reseau_social

# Swagger / OpenAPI Configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs

